// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoWESj8e0DXymKOXoPgippJ7rYAUTWQKE',
    appId: '1:208938739384:web:b085caf731d09c95f1764d',
    messagingSenderId: '208938739384',
    projectId: 'weatherproject-4cb43',
    authDomain: 'weatherproject-4cb43.firebaseapp.com',
    storageBucket: 'weatherproject-4cb43.appspot.com',
    measurementId: 'G-0V2F0YEB2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMBOw3A99aDdRoYaq5x6fNawFwSEqrxiM',
    appId: '1:208938739384:android:87975b3225c13fc9f1764d',
    messagingSenderId: '208938739384',
    projectId: 'weatherproject-4cb43',
    storageBucket: 'weatherproject-4cb43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbjKzk6EKmaK0Gup_H84IcmmKNyU_p8kM',
    appId: '1:208938739384:ios:f84db2761c77b5a3f1764d',
    messagingSenderId: '208938739384',
    projectId: 'weatherproject-4cb43',
    storageBucket: 'weatherproject-4cb43.appspot.com',
    androidClientId: '208938739384-77qvairhp8a7108lbqghmcjiqf24be3f.apps.googleusercontent.com',
    iosClientId: '208938739384-ni9olgm512ge3qblauin0b2veklagv93.apps.googleusercontent.com',
    iosBundleId: 'com.example.weartherproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbjKzk6EKmaK0Gup_H84IcmmKNyU_p8kM',
    appId: '1:208938739384:ios:67dd01d59c6e5fa0f1764d',
    messagingSenderId: '208938739384',
    projectId: 'weatherproject-4cb43',
    storageBucket: 'weatherproject-4cb43.appspot.com',
    androidClientId: '208938739384-77qvairhp8a7108lbqghmcjiqf24be3f.apps.googleusercontent.com',
    iosClientId: '208938739384-ksehl7gbh4d3lcsfdflnp30g3dlthv04.apps.googleusercontent.com',
    iosBundleId: 'com.example.weartherproject.RunnerTests',
  );
}
